# Generated by Django 4.0.5 on 2022-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetgroup',
            old_name='groupID',
            new_name='dataSetGroupId',
        ),
        migrations.RenameField(
            model_name='datasetgroup',
            old_name='groupName',
            new_name='dataSetGroupName',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='D_GroupID',
            new_name='dataSetGroupId',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='D_TypeID',
            new_name='metadataGroupId',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='D_MetadataID',
            new_name='metadataId',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='D_PROVINCE',
            new_name='provinceId',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='D_DATE',
            new_name='updateDate',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='D_TIME',
            new_name='updateTime',
        ),
        migrations.RenameField(
            model_name='metadatagroup',
            old_name='typeID',
            new_name='metadataGroupId',
        ),
        migrations.RenameField(
            model_name='metadatagroup',
            old_name='typeName',
            new_name='metadataGroupName',
        ),
        migrations.RemoveField(
            model_name='agencydatadetail',
            name='access_level',
        ),
        migrations.AddField(
            model_name='metadata',
            name='dataName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
