# Generated by Django 4.0.5 on 2022-10-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_rename_groupid_datasetgroup_datasetgroupid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agencyId', models.AutoField(primary_key=True, serialize=False)),
                ('agencyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='agencyregister',
            name='agency',
        ),
        migrations.AddField(
            model_name='agencyregister',
            name='agencyId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='acencyId',
            field=models.IntegerField(null=True),
        ),
    ]
