# Generated by Django 4.0.5 on 2022-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='D_GroupID',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
