# Generated by Django 4.0.5 on 2022-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_remove_agencyregister_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyregister',
            name='isAdmin',
        ),
        migrations.AlterField(
            model_name='agencyregister',
            name='agency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agencyregister',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='agencyregister',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
