# Generated by Django 4.0.5 on 2022-10-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_rename_acencyid_metadata_agencyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
