# Generated by Django 4.0.5 on 2022-10-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_rename_userid_agencyregister_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetgroup',
            name='dataSetGroupId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
