# Generated by Django 4.0.5 on 2022-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0008_alter_datasetgroup_datasetgroupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='dataSetGroupId',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadataGroupId',
            field=models.IntegerField(max_length=3),
        ),
    ]
