# Generated by Django 4.0.5 on 2022-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0010_metadatamapfield_metadata_stopword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='metadataGroupId',
            field=models.IntegerField(null=True),
        ),
    ]
