# Generated by Django 4.0.5 on 2022-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0011_alter_metadata_metadatagroupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='updateDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='updateTime',
            field=models.TimeField(),
        ),
    ]
