# Generated by Django 4.0.5 on 2022-11-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0012_alter_metadata_updatedate_alter_metadata_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='updateDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='updateTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
