from django.urls import path, include
from .views import (RegisterView, 
                    LoginView, 
                    UserView, 
                    LogoutView, 
                    RequestView, 
                    FileView , 
                    dropdownList, 
                    downloadFile,
                    GetMetaDataView,
                    GetFileNameByMetaDataIdView,
                    UploadNewFileView,
                    UpdataMetaDataView,
                    DeleteFileView,
                    DeleteMetaData,
                    SearchFile
                    )

urlpatterns = [
    path('register', RegisterView.as_view()),
    path('login', LoginView.as_view()),
    path('user', UserView.as_view()),
    path('logout', LogoutView.as_view()),
    path('request', RequestView.as_view()),
    path('getMetaDataView', GetMetaDataView.as_view()),
    path('uploadNewFile', UploadNewFileView.as_view()),
    path('searchFile', SearchFile.as_view()),
    path('updataMetaDataView', UpdataMetaDataView.as_view()),
    path('deleteMetaData', DeleteMetaData.as_view()),
    path('deleteFile', DeleteFileView.as_view()),
    path('getFileNameByMetaDataIdView', GetFileNameByMetaDataIdView.as_view()),
    path('upload', FileView.as_view({'post': 'create'}), name='file-upload'),
    path('dropdownlist', dropdownList),
    path('downloadFile', downloadFile),
]